# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build macOS .dmg

env:
  DEVELOPER_DIR: /Applications/Xcode_10.3.app/Contents/Developer

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Up OpenJDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with jlink
      run: ./gradlew jlink
    - name: Use jpackage to bundle macOS dmg
      run: |
        jpackage --app-version "1.0.0" \
        --copyright "Copyright 2020, example.com" \
        --description "Pew File Viewer" \
        --name "PewFileViewer" \
        --vendor "example.com" \
        --runtime-image build/image \
        --icon raw/AppIcon.icns \
        --mac-package-identifier com.example.pew \
        --mac-package-name "PewFileViewer" \
        --file-associations mac.properties \
        --module pew/com.example.pew.Launcher
    - name: Upload Artefact
      uses: actions/upload-artifact@v2.1.4
      with:
        path: ./*.dmg
